"""
RoadGuard AI - Visual Risk Engine

This module converts YOLO detection information into
an AI-estimated visual risk score.

IMPORTANT:
This is NOT physical pothole depth measurement.
It is only a visual risk estimation based on:
1. YOLO confidence
2. Relative bounding-box size
3. Vertical position in the image
"""

from dataclasses import dataclass


@dataclass
class RiskResult:
    """
    Stores the final result generated by the risk engine.
    """

    score: float
    level: str

    confidence_score: float
    size_score: float
    position_score: float

    confidence: float
    relative_area: float
    vertical_position: float


def calculate_visual_risk(
    confidence: float,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    image_width: int,
    image_height: int
) -> RiskResult:
    """
    Calculate AI-estimated visual risk for a detected pothole.

    Parameters
    ----------
    confidence : float
        YOLO confidence between 0 and 1.

    x1, y1, x2, y2 : float
        Bounding-box coordinates.

    image_width : int
        Width of the original image.

    image_height : int
        Height of the original image.

    Returns
    -------
    RiskResult
        Contains score, risk level and individual factors.
    """

    # --------------------------------------------------
    # 1. Validate input
    # --------------------------------------------------

    if image_width <= 0 or image_height <= 0:
        raise ValueError("Image width and height must be greater than zero.")

    if not 0 <= confidence <= 1:
        raise ValueError("Confidence must be between 0 and 1.")

    # --------------------------------------------------
    # 2. Calculate bounding-box dimensions
    # --------------------------------------------------

    box_width = max(0.0, x2 - x1)
    box_height = max(0.0, y2 - y1)

    # --------------------------------------------------
    # 3. Calculate bounding-box area
    # --------------------------------------------------

    box_area = box_width * box_height

    image_area = image_width * image_height

    relative_area = box_area / image_area

    # Prevent unrealistic values
    relative_area = min(max(relative_area, 0.0), 1.0)

    # --------------------------------------------------
    # 4. Confidence score
    #
    # Maximum = 50 points
    # --------------------------------------------------

    confidence_score = confidence * 50

    # --------------------------------------------------
    # 5. Size score
    #
    # Maximum = 30 points
    #
    # We use sqrt so that very large bounding boxes
    # don't dominate the entire risk score.
    # --------------------------------------------------

    size_score = min(relative_area ** 0.5, 1.0) * 30

    # --------------------------------------------------
    # 6. Vertical position
    #
    # Calculate center of bounding box.
    # --------------------------------------------------

    center_y = (y1 + y2) / 2

    vertical_position = center_y / image_height

    vertical_position = min(
        max(vertical_position, 0.0),
        1.0
    )

    # Maximum = 20 points
    position_score = vertical_position * 20

    # --------------------------------------------------
    # 7. Final risk score
    # --------------------------------------------------

    total_score = (
        confidence_score
        + size_score
        + position_score
    )

    total_score = min(
        max(total_score, 0.0),
        100.0
    )

    # --------------------------------------------------
    # 8. Convert score into risk level
    # --------------------------------------------------

    if total_score < 40:
        risk_level = "LOW"

    elif total_score < 70:
        risk_level = "MEDIUM"

    else:
        risk_level = "HIGH"

    # --------------------------------------------------
    # 9. Return result
    # --------------------------------------------------

    return RiskResult(
        score=round(total_score, 2),
        level=risk_level,

        confidence_score=round(confidence_score, 2),
        size_score=round(size_score, 2),
        position_score=round(position_score, 2),

        confidence=round(confidence, 4),
        relative_area=round(relative_area, 6),
        vertical_position=round(vertical_position, 4)
    )